### ISSUE TITLE
really man

### ISSUE THREAD

**Issue by farmerTheodor** [Coteh/wordle-clone#12]
**Describe the bug**
really man

**To Reproduce**
1. crane
2. spent
3. "really man"

**Expected behavior**
To not say "really man"

**Screenshots**
![image](https://user-images.githubusercontent.com/24848547/178171496-c4eabacf-7b10-4a9e-85b3-35a85a3db421.png)

**Desktop (please complete the following information):**
 - Browser firefox

**Additional context**
really man

**Comment by Coteh** [comment]
Wow that's actually the word today lol.

I basically grabbed all five letter words from the popular dictionary textfile in this repo: https://github.com/dolph/dictionary

I was thinking about finding a new dictionary at some point. I can also consider removing these types of words while at it to make it more appropriate/family friendly.

**Comment by farmerTheodor** [comment]
Not going to lie I gave a chuckle so no need to go changing things
