### ISSUE TITLE
LOL what word list are you using? 

### ISSUE THREAD

**Issue by farmerTheodor** [Coteh/wordle-clone#81]
![image](https://github.com/Coteh/wordle-clone/assets/24848547/3764d093-5256-4e9f-99b7-6412dfae9602)

**Comment by Coteh** [comment]
A very naughty one it looks like lol 😛 

I used all five letter words from the `popular.txt` word list from here https://github.com/dolph/dictionary

**Comment by farmerTheodor** [comment]
Fair enough
